# Generated by Django 5.1.4 on 2024-12-06 15:05

import product.helps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=product.helps.SaveImages.product_images_path),
            preserve_default=False,
        ),
    ]
